// Mighty Wash uniform catalog, mirrored from the WashLyfe Shopify collection
// (washlyfe.myshopify.com/collections/mighty-wash). Static product data used by
// the Uniforms page catalog + request form. Prices are the listed USD; where
// variants differ, priceMax holds the top of the range.

export type UniformProduct = {
  name: string
  brand: string
  price: number
  priceMax: number | null
  sizes: string[]
  colors: string[]
  image: string | null
  url: string
}

export const UNIFORM_CATALOG: UniformProduct[] = [
  { name: 'Sales Polo Bundle (Quantity 4)', brand: 'Sport-Tek', price: 66, priceMax: 70, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Carolina Blue'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07133144.png', url: 'https://washlyfe.myshopify.com/products/sales-polo-bundle-quantity-4' },
  { name: 'Management Polo Bundle (Quantity 4)', brand: 'Sport-Tek', price: 66, priceMax: 78, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['True Red'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-06153359.png', url: 'https://washlyfe.myshopify.com/products/management-polo-bundle-quantity-4' },
  { name: 'Port Authority Core Soft Shell Jacket', brand: 'Port Authority', price: 43, priceMax: 48, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL'], colors: ['Dress Blue Nvy', 'Black'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07023244.png', url: 'https://washlyfe.myshopify.com/products/port-authority-ladies-core-soft-shell-jacket' },
  { name: 'Port Authority Ladies Core Soft Shell Jacket', brand: 'Port Authority', price: 43, priceMax: 47, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black', 'Dress Blue Navy'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07023959.png', url: 'https://washlyfe.myshopify.com/products/port-authority-core-soft-shell-jacket-2' },
  { name: 'Port Authority Outdoor Wide-Brim Hat 2', brand: 'Port Authority', price: 22, priceMax: null, sizes: [], colors: ['Gray'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07120927.png', url: 'https://washlyfe.myshopify.com/products/port-authority-outdoor-wide-brim-hat-2' },
  { name: 'Tunnel Polo Bundle (Quantity 4)', brand: 'Sport-Tek', price: 66, priceMax: null, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['True Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07164836.png', url: 'https://washlyfe.myshopify.com/products/tunnel-polo-bundle-quantity-4' },
  { name: 'Ladies Sales Polo Bundle (Quantity 4)', brand: 'Sport-Tek', price: 66, priceMax: 70, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Carolina Blue'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot_2025-11-06_152250.png', url: 'https://washlyfe.myshopify.com/products/ladies-sales-polo-bundle-quantity-4' },
  { name: 'Ladies Management Polo Bundle (Quantity 4)', brand: 'Sport-Tek', price: 66, priceMax: 70, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['True Red'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot_2025-11-06_151801.png', url: 'https://washlyfe.myshopify.com/products/ladies-management-polo-bundle-quantity-4' },
  { name: 'Ladies Tunnel Polo Bundle (Quantity 4).', brand: 'Sport-Tek', price: 66, priceMax: 70, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['True Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-06152919.png', url: 'https://washlyfe.myshopify.com/products/ladies-tunnel-polo-bundle-quantity-4' },
  { name: 'Sport-Tek V-Neck Raglan Wind Shirt', brand: 'Sport-Tek', price: 25, priceMax: 30, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL'], colors: ['True Navy', 'True Red', 'True Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07163736.png', url: 'https://washlyfe.myshopify.com/products/sport-tek-v-neck-raglan-wind-shirt' },
  { name: 'Snapback Trucker Cap 2', brand: 'Richardson', price: 14, priceMax: null, sizes: [], colors: ['Black', 'Royal White'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07154032.png', url: 'https://washlyfe.myshopify.com/products/snapback-trucker-cap-2' },
  { name: 'TravisMathew Bayfront Solid Polo TM1MY399', brand: 'TRAVISMATHEW', price: 68, priceMax: null, sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'], colors: ['Black', 'InsBlue', 'Roan Rouge'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07164454.png', url: 'https://washlyfe.myshopify.com/products/travismathew-bayfront-solid-polo-tm1my399' },
  { name: 'The Wrightson Cap', brand: 'Imperial', price: 25, priceMax: null, sizes: [], colors: ['Black White', 'White'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07164241.png', url: 'https://washlyfe.myshopify.com/products/the-wrightson-cap' },
  { name: 'Sport-Tek Repeat 1/2-Zip Short Sleeve Jacket JST489', brand: 'Sport-Tek', price: 23, priceMax: 27, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black', 'Deep Red', 'True Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07163008.png', url: 'https://washlyfe.myshopify.com/products/sport-tek-repeat-1-2-zip-short-sleeve-jacket-jst489' },
  { name: 'Sport-Tek PosiCharge Tough Mesh Full-Button Jersey', brand: 'Sport-Tek', price: 18, priceMax: 22, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black', 'True Red', 'True Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07160745.png', url: 'https://washlyfe.myshopify.com/products/sport-tek-posicharge-tough-mesh-full-button-jersey' },
  { name: 'Sport-Tek PosiCharge Competitor 1/4-Zip Pullover', brand: 'Sport-Tek', price: 15, priceMax: 19, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black', 'True Red', 'True Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07160320.png', url: 'https://washlyfe.myshopify.com/products/sport-tek-posicharge-competitor-1-4-zip-pullover' },
  { name: 'Sport-Tek Ladies Active Textured Polo', brand: 'Sport-Tek', price: 20, priceMax: 24, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black', 'True Red', 'True Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07155743.png', url: 'https://washlyfe.myshopify.com/products/sport-tek-ladies-active-textured-polo' },
  { name: 'Sport-Tek Ladies Active Textured Colorblock Polo', brand: 'Sport-Tek', price: 20, priceMax: 24, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black Grey'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07155332.png', url: 'https://washlyfe.myshopify.com/products/sport-tek-ladies-active-textured-colorblock-polo' },
  { name: 'Sport-Tek ® Posi-UV ® Pro Long Sleeve Tee', brand: 'Sport-Tek', price: 20, priceMax: 24, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black', 'True Red', 'True Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07154828.png', url: 'https://washlyfe.myshopify.com/products/sport-tek-®-posi-uv-®-pro-long-sleeve-tee' },
  { name: 'Snapback Trucker Cap', brand: 'Richardson', price: 16, priceMax: null, sizes: [], colors: ['Black', 'Heather Grey Red', 'Royal White'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07154359.png', url: 'https://washlyfe.myshopify.com/products/snapback-trucker-cap' },
  { name: 'Sales Polo Bundle Black (Quantity 4)', brand: 'Sport-Tek', price: 66, priceMax: 70, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07153806.png', url: 'https://washlyfe.myshopify.com/products/sales-polo-bundle-black-quantity-4' },
  { name: 'Printed Mesh-Back Trucker Cap', brand: 'Richardson', price: 18, priceMax: null, sizes: [], colors: ['Black Black to White Fade', 'Red Red to White Fade', 'Royal Royal to White Fade'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07132726.png', url: 'https://washlyfe.myshopify.com/products/printed-mesh-back-trucker-cap' },
  { name: 'PosiCharge Competitor Hooded Pullover', brand: 'Sport-Tek', price: 18, priceMax: 22, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black', 'True Red', 'True Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07132216.png', url: 'https://washlyfe.myshopify.com/products/posicharge-competitor-hooded-pullover' },
  { name: 'Port Authority Silk Touch Polo', brand: 'Port Authority', price: 15, priceMax: 19, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL'], colors: ['Black', 'Red', 'Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07123023.png', url: 'https://washlyfe.myshopify.com/products/port-authority-silk-touch-polo' },
  { name: 'Port Authority R-Tek Stretch Fleece Headband - BLANK NO LOGO', brand: 'Port Authority', price: 6, priceMax: null, sizes: [], colors: ['Black'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Original_30.jpg', url: 'https://washlyfe.myshopify.com/products/port-authority-r-tek-stretch-fleece-headband-blank-no-logo' },
  { name: 'Port Authority Packable Puffy Jacket J850', brand: 'Port Authority', price: 48, priceMax: 52, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Cobalt Blue', 'Deep Black', 'Fire Red Graph'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07121807.png', url: 'https://washlyfe.myshopify.com/products/port-authority-packable-puffy-jacket-j850' },
  { name: 'Port Authority Outdoor Wide-Brim Hat', brand: 'Port Authority', price: 22, priceMax: null, sizes: [], colors: ['Dress Blue Nvy'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07121132.png', url: 'https://washlyfe.myshopify.com/products/port-authority-outdoor-wide-brim-hat' },
  { name: 'Port Authority Ladies Textured Crepe Blouse LW714', brand: 'Port Authority', price: 36, priceMax: 40, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Aegean Blue', 'Deep Black'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07120140.png', url: 'https://washlyfe.myshopify.com/products/port-authority-ladies-textured-crepe-blouse-lw714' },
  { name: 'Port Authority Ladies Long Sleeve Button-Front Blouse', brand: 'Port Authority', price: 36, priceMax: 40, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07024451.png', url: 'https://washlyfe.myshopify.com/products/port-authority-ladies-long-sleeve-button-front-blouse' },
  { name: 'Port Authority Ladies 3/4-Sleeve Tunic Blouse', brand: 'Port Authority', price: 36, priceMax: 40, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Sterling Grey', 'Black', 'Ivory Chiffon', 'True Blue', 'True Navy'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07021718.png', url: 'https://washlyfe.myshopify.com/products/port-authority-ladies-3-4-sleeve-tunic-blouse' },
  { name: 'OGIO Gravitate Polo', brand: 'Ogio', price: 33, priceMax: 37, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Navy Heather', 'Dark Hthr Grey'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07021224.png', url: 'https://washlyfe.myshopify.com/products/ogio-gravitate-polo' },
  { name: 'OGIO Evolution Polo OG147', brand: 'Ogio', price: 28, priceMax: 32, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['RiverBlNv', 'Blacktop'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07020613.png', url: 'https://washlyfe.myshopify.com/products/ogio-evolution-polo-og147' },
  { name: 'Nike Ladies Victory Solid Polo NKDX6685', brand: 'Nike', price: 68, priceMax: 70, sizes: ['S', 'M', 'L', 'XL', '2XL'], colors: ['Black', 'ColNavy', 'CoolGrey'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07014914.png', url: 'https://washlyfe.myshopify.com/products/nike-ladies-victory-solid-polo-nkdx6685' },
  { name: 'Nike Golf Dri-FIT Embossed Tri-Blade Polo', brand: 'Nike Golf', price: 38, priceMax: 42, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black', 'Old Royal', 'University Red'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07013823.png', url: 'https://washlyfe.myshopify.com/products/nike-golf-dri-fit-embossed-tri-blade-polo' },
  { name: 'Nike Dri-FIT Vapor Space Dyed Polo NKDC2109', brand: 'Nike', price: 68, priceMax: 72, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Anthracite', 'Navy'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07013245.png', url: 'https://washlyfe.myshopify.com/products/nike-dri-fit-vapor-space-dyed-polo-nkdc2109' },
  { name: 'Nike Dri-FIT Vapor Block Polo NKDC2114', brand: 'Nike', price: 58, priceMax: 61, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Anthracite', 'Wolf Grey'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07011608.png', url: 'https://washlyfe.myshopify.com/products/nike-dri-fit-vapor-block-polo-nkdc2114' },
  { name: 'Next Level  Women\'s Tri-Blend Tee', brand: 'Next Level', price: 12, priceMax: 14, sizes: ['S', 'M', 'L', 'XL', '2XL'], colors: ['White', 'Black', 'Red', 'Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07010923.png', url: 'https://washlyfe.myshopify.com/products/next-level-womens-tri-blend-tee' },
  { name: 'Mercer+Mettle Women\'s Open Front Cardigan Sweater MM3023', brand: 'Mercer+Mettle', price: 53, priceMax: 57, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Birch', 'Deep Black', 'Gusty Grey Heather'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07010125.png', url: 'https://washlyfe.myshopify.com/products/mercer-mettle-womens-open-front-cardigan-sweater-mm3023' },
  { name: 'Mercer+Mettle Stretch Jersey Long Sleeve Shirt MM1018', brand: 'Mercer+Mettle', price: 38, priceMax: 42, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Anchor Grey', 'AnrGGoDmnd', 'Deep Black', 'InsBlue', 'NvyGeoDmnd'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-07004722.png', url: 'https://washlyfe.myshopify.com/products/mercer-mettle-stretch-jersey-long-sleeve-shirt-mm1018' },
  { name: 'Men\'s Zone Performance Polo', brand: 'Team 365', price: 15, priceMax: 19, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL', '6XL'], colors: ['Black', 'Sport Red', 'Sport Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot_2025-11-07_003716.png', url: 'https://washlyfe.myshopify.com/products/mens-zone-performance-polo' },
  { name: 'Men\'s Tamiami™ II Short-Sleeve Shirt', brand: 'Columbia', price: 58, priceMax: 61, sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'], colors: ['White', 'Cool Grey', 'Fossil', 'Gulf Stream', 'Sail', 'Vivid Blue'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot_2025-11-07_002543.png', url: 'https://washlyfe.myshopify.com/products/mens-tamiami™-ii-short-sleeve-shirt' },
  { name: 'Men\'s Tamiami™ II Long-Sleeve Shirt', brand: 'Columbia', price: 68, priceMax: 71, sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'], colors: ['White', 'Cool Grey', 'Fossil', 'Gulf Stream', 'Sail', 'Vivid Blue'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot_2025-11-07_001043.png', url: 'https://washlyfe.myshopify.com/products/mens-tamiami™-ii-long-sleeve-shirt' },
  { name: 'Ladies Sales Polo Bundle Black (Quantity 4)', brand: 'Sport-Tek', price: 66, priceMax: 70, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot_2025-11-06_152511.png', url: 'https://washlyfe.myshopify.com/products/ladies-sales-polo-bundle-black-quantity-4' },
  { name: 'Ladies Broadcloth Gingham Easy Care Shirt', brand: 'Port Authority', price: 38, priceMax: 42, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black White', 'Gusty Grey White', 'True Navy White', 'True Royal White'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-05235332.png', url: 'https://washlyfe.myshopify.com/products/ladies-broadcloth-gingham-easy-care-shirt' },
  { name: 'Gildan Heavy Cotton 100% Cotton T-Shirt emb', brand: 'Gildan', price: 10, priceMax: 13, sizes: ['Youth S', 'Youth M', 'Youth L', 'Youth XL', 'XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'], colors: ['Black', 'Red', 'Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-05234343.png', url: 'https://washlyfe.myshopify.com/products/gildan-heavy-cotton-100-cotton-t-shirt-emb' },
  { name: 'Gildan Heavy Blend Crewneck Sweatshirt emb', brand: 'Gildan', price: 16, priceMax: 19, sizes: ['S', 'M', 'XL', '2XL', '3XL'], colors: ['Red', 'Carolina Blue', 'Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-05233409.png', url: 'https://washlyfe.myshopify.com/products/gildan-heavy-blend-crewneck-sweatshirt-emb' },
  { name: 'Era Cage Short Sleeve 1/4-Zip Jacket', brand: 'New Era Apparel', price: 33, priceMax: 37, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['True Navy', 'Black', 'Graphite', 'Royal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot2025-11-05232303.png', url: 'https://washlyfe.myshopify.com/products/era-cage-short-sleeve-1-4-zip-jacket' },
  { name: 'dt5001', brand: 'District', price: 10, priceMax: 14, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black', 'Deep Royal', 'New Red'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot_2025-11-05_231416.png', url: 'https://washlyfe.myshopify.com/products/dt5001' },
  { name: 'District Made Ladies Perfect Tri 3/4-Sleeve Raglan', brand: 'District Made', price: 14, priceMax: 17, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black Frost', 'Red Frost', 'Royal Frost'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/Screenshot_2025-11-05_225744.png', url: 'https://washlyfe.myshopify.com/products/district-made-ladies-perfect-tri-3-4-sleeve-raglan' },
  { name: 'District Made  Mens Perfect Tr V-Neck Tee', brand: 'District Made', price: 9, priceMax: 13, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Black Frost', 'Red Frost', 'Royal Frost'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/1.png', url: 'https://washlyfe.myshopify.com/products/district-made-mens-perfect-tr-v-neck-tee' },
  { name: 'Carhartt Crowley Soft Shell Jacket', brand: 'Carhartt', price: 123, priceMax: 126, sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'], colors: ['Black', 'charcoal'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/brave_screenshot_stores.inksoft.com_4_b1a37add-4be1-4a67-a5ed-94d46fc8f397.png', url: 'https://washlyfe.myshopify.com/products/carhartt-crowley-soft-shell-jacket' },
  { name: 'Broadcloth Gingham Easy Care Shirt', brand: 'Port Authority', price: 40, priceMax: 44, sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['True Royal White'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/brave_screenshot_stores.inksoft.com.png', url: 'https://washlyfe.myshopify.com/products/broadcloth-gingham-easy-care-shirt' },
  { name: '6.1 Ounce Ringspun Cotton Long Sleeve T-Shirt emb', brand: 'Comfort Colors', price: 25, priceMax: null, sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL'], colors: ['Blue Jean', 'Denim', 'Pepper'], image: 'https://cdn.shopify.com/s/files/1/0786/0142/1059/files/brave_screenshot_stores.inksoft.com_1_b358dea0-846d-49e9-adc7-8678f3db5260.png', url: 'https://washlyfe.myshopify.com/products/6-1-ounce-ringspun-cotton-long-sleeve-t-shirt-emb' },
]
