import { format } from 'date-fns'
import { loadPdfLogo, placePdfLogo } from '@/lib/pdfLogo'
import type { ReportSpec } from '@/lib/queries/askOperator'

// Renders an Operator AI report spec to a branded PDF and triggers a download.
// jspdf + jspdf-autotable are heavy, so they load on demand only here.

const ACCENT: [number, number, number] = [37, 99, 235] // brand blue (#2563eb)
const MUTED = 120
const MARGIN = 14

type Doc = import('jspdf').jsPDF & { lastAutoTable?: { finalY: number } }

const fileSafe = (s: string) =>
  s.replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'report'

export async function downloadReportPdf(
  spec: ReportSpec,
  opts?: { brandLogoUrl?: string | null; accountName?: string },
): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default
  const logo = await loadPdfLogo(opts?.brandLogoUrl)

  const doc = new jsPDF() as Doc
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  placePdfLogo(doc, logo)

  // Title block.
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(17)
  doc.setTextColor(20)
  doc.text(spec.title, MARGIN, 18)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(MUTED)
  const meta = [spec.subtitle, opts?.accountName, `Generated ${format(new Date(), 'PP')}`]
    .filter(Boolean)
    .join('  ·  ')
  doc.text(meta, MARGIN, 25)

  // Accent rule under the header.
  doc.setDrawColor(...ACCENT)
  doc.setLineWidth(0.6)
  doc.line(MARGIN, 29, pageW - MARGIN, 29)

  const common = {
    styles: { fontSize: 9, cellPadding: 2.5, overflow: 'linebreak' as const },
    headStyles: { fillColor: ACCENT, fontStyle: 'bold' as const },
    alternateRowStyles: { fillColor: [247, 248, 250] as [number, number, number] },
    margin: { left: MARGIN, right: MARGIN },
  }

  let y = 37
  const ensure = (needed: number) => {
    if (y + needed > pageH - 16) {
      doc.addPage()
      y = 18
    }
  }
  const afterTable = () => (doc.lastAutoTable?.finalY ?? y) + 8

  for (const section of spec.sections ?? []) {
    if (section.heading) {
      ensure(12)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(12)
      doc.setTextColor(20)
      doc.text(section.heading, MARGIN, y)
      y += 6
    }

    if (section.type === 'text' && section.body) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      doc.setTextColor(60)
      const lines = doc.splitTextToSize(section.body, pageW - MARGIN * 2) as string[]
      ensure(lines.length * 5 + 4)
      doc.text(lines, MARGIN, y)
      y += lines.length * 5 + 6
    } else if (section.type === 'table' && section.columns?.length) {
      ensure(20)
      autoTable(doc, {
        ...common,
        startY: y,
        head: [section.columns],
        body: (section.rows ?? []).map((r) => section.columns!.map((_, i) => r[i] ?? '')),
      })
      y = afterTable()
    } else if (section.type === 'stats' && section.items?.length) {
      // Render figures as a two-column key/value table — clean and compact.
      ensure(20)
      autoTable(doc, {
        ...common,
        startY: y,
        head: [['Metric', 'Value']],
        body: section.items.map((it) => [it.label, it.value]),
        columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
      })
      y = afterTable()
    }
  }

  // Footer on every page.
  const pages = doc.getNumberOfPages()
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text('Generated by Operator AI', MARGIN, pageH - 8)
    doc.text(`Page ${p} of ${pages}`, pageW - MARGIN, pageH - 8, { align: 'right' })
  }

  doc.save(`${fileSafe(spec.title)}-${format(new Date(), 'yyyy-MM-dd')}.pdf`)
}
