export type SignageCategory = {
  slug: string
  name: string
  // Second-level options shown in the vendor's flyout for this category.
  // Sizes and pricing per option come next.
  items: string[]
}

// Mirrored from the sign vendor's "Select Products" menu (sharperprinting.com).
// Order matches the vendor's site. `items` are the options under each category.
export const SIGNAGE_CATEGORIES: SignageCategory[] = [
  {
    slug: 'specialty-printing-products',
    name: 'Specialty Printing Products',
    items: [
      '15 oz. Vinyl Banners DS (Mascot Junction)',
      '15 oz. Vinyl Banners SS (Mascot Junction)',
      'Extra High Tac Vinyl',
      'Low Tac Vinyl (Mascot Junction)',
      'MAG X (Mascot Junction)',
      'Magnets Dry Erase (Mascot Junction)',
      'Magnets (Mascot Junction)',
      'Marine Vinyl Bottom (MBS)',
      'Marine Vinyl Nose (MBS)',
      'Multishield (Mascot Junction)',
      'Thought Bubbles - Controltac (Mascot Junction)',
    ],
  },
  {
    slug: 'banners',
    name: 'Banners',
    items: [
      '13 oz. Vinyl Banners',
      '15 oz. Vinyl Banners',
      '18 oz. Vinyl Banners',
      'Mesh Banners',
    ],
  },
  {
    slug: 'flags',
    name: 'Flags',
    items: [
      'Angled Feather Flags',
      'Convex Feather Flags',
      'Econo Feather Flags',
      'Pole Flags',
      'Teardrop Flags',
      'Wholesale Rectangular Feather Flags',
    ],
  },
  {
    slug: 'hardware',
    name: 'Hardware',
    // Screenshot pending.
    items: [],
  },
  {
    slug: 'yard-signs',
    name: 'Yard Signs',
    items: ['H-Stakes Heavy Duty', 'H-Stakes for Yard Signs', 'Yard Signs'],
  },
  {
    slug: 'banner-stands',
    name: 'Banner Stands',
    items: [
      'Clear Deluxe Retractable Banner Stand',
      'Clear Standard Retractable Banner Stand',
      'Deluxe Retractable Banner Stand - Double Sided',
      'Deluxe Retractable Banner Stand - Single Sided',
      'Mini Retractable Banner Stand',
      'Miniature X-Stand Banner',
      'SD Retractable Banner Stand',
      'Standard Retractable Banner Stand',
      'X-Stand Display Banner',
    ],
  },
  {
    slug: 'tradeshow-printing',
    name: 'Tradeshow Printing',
    items: [
      '8-Foot Custom Tablecloth',
      'Custom 6-Foot Table Cover',
      'Economy Tube Display (Step & Repeat)',
      'Event Tent',
      'Floor Mat',
      'Heavy Duty Tube Display (Step & Repeat)',
      'Rigid Substrate M Base',
      'Table Runner',
      "Tension Fabric Display - 6' Curved",
      "Tension Fabric Display - 8' & 10' Curved",
      'Tension Fabric Display - Straight',
      'Tension Fabric Stand',
      'Velcro Fabric Display - Curved',
      'Velcro Fabric Pop-Up Display - Straight',
      'Xanita Board',
    ],
  },
  {
    slug: 'adhesive-vinyl-products',
    name: 'Adhesive Vinyl Products',
    items: [
      '3M™ 40C Controltac™ Print Film',
      'Adhesive Vinyl',
      'Air Release Gloss Vinyl',
      'AlumiGraphics® GRIP',
      'AlumiGraphics® SMOOTH',
      'Brick Vinyl',
      'Car Wrap Vinyl - 3M 180',
      'Car Wrap Vinyl - 3M 480',
      'Clear Adhesive Vinyl Film',
      'Embossed Wall Vinyl',
      'Extra High Tac Vinyl',
      'Front Mount Adhesive',
      'Frosted Vinyl',
      'Glass Apeel',
      'Photo Tex',
      'Photo Tex EX High Tack',
      'Polar Smooth 150 Air',
      'Reflective Adhesive Vinyl',
      'Static Cling Vinyl Film',
      'Stickers',
      'Translucent Vinyl',
      'TwoWay Vision',
      'Window Perf (Exterior Mount)',
      'Window Perf (Interior Mount - Clear)',
      'panoRama Walk & Wall',
    ],
  },
  {
    slug: 'floor-adhesive-products',
    name: 'Floor Adhesive Products',
    items: [
      'Carpet Vinyl',
      'Embossed Floor Vinyl',
      'FloorAppeal',
      'Sidewalk Graphics Media',
    ],
  },
  {
    slug: 'rigid-substrates',
    name: 'Rigid Substrates',
    items: [
      '1/4" Clear Acrylic',
      '1/4" White Acrylic',
      '3/16" Clear Acrylic',
      '3/16" White Acrylic',
      'Aluminum',
      'Bubble X',
      'Bulldog Board Material - 3mm C2S',
      'Coroplast - 10mm',
      'Coroplast - 4mm',
      'Foam Core',
      'Foam PVC - 3mm',
      'Foam PVC - 6mm',
      'Gatorplast - 1/2" White',
      'Gatorplast - 3/16" White',
      'Max Metal - 3mm',
      'Max Metal - 6mm',
      'Multishield',
      'Polycarbonate',
      'Styrene',
    ],
  },
  {
    slug: 'full-sheets',
    name: 'Full Sheets',
    items: [
      '3mm Foam PVC Full Sheets',
      '3mm Max Metal Full Sheets',
      '4mm Coroplast Full Sheets',
      'Foam Core Full Sheets',
      'Styrene Full Sheets',
    ],
  },
  {
    slug: 'magnets',
    name: 'Magnets',
    items: ['Custom Vehicle Magnets', 'Small Magnets'],
  },
  {
    slug: 'signage',
    name: 'Signage',
    items: ['Deluxe A-Frame', 'LED Backlit Polyester', 'LED Light Box Insert'],
  },
  {
    slug: 'paper-products',
    name: 'Paper Products',
    items: ['C2S 24pt Paper Board', 'Paper Poster'],
  },
  {
    slug: 'fabric',
    name: 'Fabric',
    items: ['Flag Fabric'],
  },
  {
    slug: 'art-displays',
    name: 'Art Displays',
    items: ['Canvas Wraps', 'Custom Canvas', 'Framed Print', 'Snap Poster Hanger'],
  },
  {
    slug: 'frames-and-stands',
    name: 'Frames & Stands',
    items: [
      'Banjo Frame',
      'Folding Frame',
      'Outdoor Sidewalk Sign',
      'Rigid Product M Base',
      'T-Bar Stake',
    ],
  },
]
